// Textes du mode enfant (10-12 ans) : window.SAISON_ENFANTS.produits[slug] et .lexique[id]
(function () {
  function K(titre, intro, quiz, hist, ou, sais, bon, defi) { return { titre: titre, intro: intro, quiz: quiz, hist: hist, ou: ou, sais: sais, bon: bon, defi: defi }; }
  var produits = {
    carotte: K('La carotte', 'Croquante et sucrée, la carotte se garde très longtemps : on en trouve toute l’année, mais elle est meilleure en automne.',
      ['Quelle couleur avaient les premières carottes ?', ['Orange', 'Violette ou jaune', 'Bleue'], 1, 'Les premières carottes étaient violettes ou jaunes ! Les carottes orange ont été créées aux Pays-Bas il y a environ 400 ans.'],
      'La carotte vient d’Asie centrale, autour de l’Afghanistan. Il y a très longtemps, on la cultivait surtout pour ses feuilles et ses graines, qui servaient de médicament.',
      'Elle aime la terre sableuse et légère. En France, elle pousse beaucoup dans les Landes, en Normandie et en Bretagne.',
      'La carotte est une racine : la partie qu’on mange pousse sous la terre, et seules ses feuilles dépassent !',
      [['👀', 'Bonne pour les yeux', 'Son bêta-carotène aide tes yeux à mieux voir quand il fait sombre.'], ['🦷', 'Croquante', 'La croquer crue fait travailler tes dents.'], ['⚡', 'Pleine d’énergie', 'Naturellement sucrée, elle est parfaite au goûter.']],
      ['Bâtonnets de carotte et houmous', ['Demande à un adulte d’éplucher les carottes.', 'Coupe-les en bâtonnets avec un couteau à bout rond.', 'Verse un peu de houmous dans un bol.', 'Trempe et croque !']]),
    tomate: K('La tomate', 'Rouge, juteuse et sucrée, la tomate est la reine de l’été. En hiver, elle n’a presque pas de goût : mieux vaut l’attendre !',
      ['La tomate, c’est un fruit ou un légume ?', ['Un fruit', 'Un légume', 'Les deux !'], 2, 'Pour les botanistes, c’est un fruit, car elle contient des graines. Mais en cuisine, on la prépare comme un légume.'],
      'La tomate vient d’Amérique du Sud, dans les montagnes des Andes. Arrivée en Europe il y a environ 500 ans, on a d’abord cru qu’elle était toxique et on la plantait juste pour décorer !',
      'Elle a besoin de beaucoup de soleil et de chaleur. En France, on la cultive surtout dans le Sud-Est et en Bretagne.',
      'Il existe des milliers de variétés de tomates : rouges, jaunes, vertes, noires et même rayées !',
      [['❤️', 'Bonne pour le cœur', 'Son pigment rouge, le lycopène, protège ton corps.'], ['💧', 'Pleine d’eau', 'Elle est faite à 94 % d’eau : idéale quand il fait chaud.'], ['🛡️', 'Vitamine C', 'Elle aide ton corps à se défendre contre les microbes.']],
      ['Brochettes tomate-mozzarella', ['Lave des tomates cerises.', 'Coupe les billes de mozzarella en deux si elles sont grosses.', 'Pique une tomate, une feuille de basilic et une mozzarella sur un bâtonnet.', 'Ajoute un filet d’huile d’olive.']]),
    aubergine: K('L’aubergine', 'Avec sa peau violette toute brillante, l’aubergine est un légume d’été. Crue, elle n’est pas bonne : il faut toujours la cuire !',
      ['Pourquoi s’appelle-t-elle « eggplant » (plante à œufs) en anglais ?', ['Elle pond des œufs', 'Les premières ressemblaient à des œufs blancs', 'Elle est jaune comme un jaune d’œuf'], 1, 'Les premières aubergines connues en Angleterre étaient petites, rondes et blanches… comme des œufs !'],
      'L’aubergine vient d’Inde, où on la cultive depuis plus de 4 000 ans. Elle est arrivée en France par l’Espagne et l’Italie.',
      'Elle adore la chaleur. En France, elle pousse surtout dans le Sud : en Provence et dans le Roussillon.',
      'L’aubergine est une cousine de la tomate et de la pomme de terre : elles sont toutes de la même famille, les Solanacées.',
      [['🌾', 'Des fibres', 'Elles aident ton ventre à bien fonctionner.'], ['🪶', 'Très légère', 'Elle a très peu de calories… tant qu’on ne met pas trop d’huile !'], ['🟣', 'Peau violette', 'Sa couleur vient d’antioxydants qui protègent tes cellules.']],
      ['Caviar d’aubergine', ['Un adulte fait cuire l’aubergine entière au four pendant 40 minutes.', 'Quand elle a refroidi, récupère la chair avec une cuillère.', 'Écrase-la à la fourchette avec de l’huile d’olive, du sel et un peu de citron.', 'Tartine sur du pain grillé !']]),
    courgette: K('La courgette', 'Douce et facile à cuisiner, la courgette pousse si vite en été que les jardiniers ne savent plus quoi en faire !',
      ['Que veut dire « courgette » ?', ['Petite courge', 'Qui court vite', 'Légume vert'], 0, 'Courgette veut dire « petite courge » : c’est une courge qu’on cueille quand elle est encore jeune.'],
      'La courgette vient des courges d’Amérique. Ce sont les Italiens qui ont eu l’idée de les cueillir toutes petites, il y a environ 200 ans.',
      'En France, elle pousse surtout dans le Sud-Est, mais on en trouve dans presque tous les potagers en été.',
      'Ses grosses fleurs jaunes se mangent aussi ! On peut les farcir ou les faire en beignets.',
      [['💧', 'Pleine d’eau', 'Elle est faite à 95 % d’eau.'], ['🪶', 'Très légère', 'L’un des légumes les plus légers : tu peux en manger beaucoup !'], ['💪', 'Du potassium', 'Il aide tes muscles à bien fonctionner.']],
      ['Rubans de courgette', ['Lave une courgette.', 'Avec un éplucheur, fais de longs rubans.', 'Ajoute un peu d’huile d’olive, du citron et du sel.', 'Mélange et mange tout de suite, cru !']]),
    concombre: K('Le concombre', 'Frais et croquant, le concombre est le légume parfait pour se rafraîchir en été.',
      ['Combien d’eau contient un concombre ?', ['50 %', '75 %', 'Plus de 95 %'], 2, 'Le concombre est l’un des aliments qui contiennent le plus d’eau : presque 96 % !'],
      'Le concombre vient d’Inde, où on le cultive depuis plus de 3 000 ans. Les Romains l’adoraient : l’empereur Tibère en mangeait tous les jours !',
      'En France, il pousse surtout dans l’Ouest, en Pays de la Loire et en Bretagne, souvent sous des serres.',
      'Le concombre est un cousin du melon et de la courgette : ils sont tous de la famille des Cucurbitacées.',
      [['💧', 'Super hydratant', 'Il désaltère presque autant qu’un verre d’eau.'], ['🪶', 'Très léger', 'Il n’a presque pas de calories.'], ['🦴', 'Vitamine K', 'Elle aide à garder des os solides.']],
      ['Tzatziki express', ['Râpe un demi-concombre et presse-le pour enlever l’eau.', 'Mélange-le avec un yaourt grec.', 'Ajoute un peu de menthe, du sel et un filet de citron.', 'Trempe des bâtonnets de pain dedans !']]),
    poivron: K('Le poivron', 'Vert, jaune, orange ou rouge : le poivron met de la couleur dans l’assiette à la fin de l’été.',
      ['Un poivron vert et un poivron rouge, c’est…', ['Deux plantes différentes', 'Souvent le même, mais plus ou moins mûr', 'Le rouge est peint'], 1, 'Le poivron vert n’est pas encore mûr. En restant au soleil, il devient jaune ou rouge, et de plus en plus sucré !'],
      'Le poivron vient d’Amérique centrale. C’est Christophe Colomb qui l’a rapporté en Europe, il y a plus de 500 ans.',
      'Il aime la chaleur : en France, il pousse surtout dans le Sud-Est et le Sud-Ouest.',
      'Le poivron rouge contient plus de vitamine C qu’une orange !',
      [['🛡️', 'Champion de la vitamine C', 'Elle aide ton corps à combattre les microbes.'], ['👀', 'Bon pour les yeux', 'Les poivrons rouges et orange sont riches en bêta-carotène.'], ['🌾', 'Des fibres', 'Pour un ventre en pleine forme.']],
      ['Bâtonnets arc-en-ciel', ['Lave un poivron rouge, un jaune et un vert.', 'Demande à un adulte de les couper en deux et d’enlever les graines.', 'Coupe-les en bâtonnets.', 'Trempe-les dans du fromage blanc aux herbes !']]),
    piment: K('Le piment', 'Petit mais très costaud, le piment pique la langue ! On l’utilise en toute petite quantité pour donner du goût.',
      ['Pour calmer une bouche qui brûle à cause du piment, il vaut mieux boire…', ['De l’eau', 'Du lait', 'Du soda'], 1, 'Le lait calme le feu du piment bien mieux que l’eau, qui ne fait qu’étaler la brûlure.'],
      'Le piment vient d’Amérique du Sud, où on le mange depuis plus de 6 000 ans. Christophe Colomb l’a rapporté en Europe.',
      'En France, le plus célèbre est le piment d’Espelette, cultivé au Pays basque et protégé par une AOP.',
      'Ce qui pique dans le piment s’appelle la capsaïcine. Les oiseaux ne la sentent pas : ils peuvent en manger sans problème !',
      [['🛡️', 'Vitamine C', 'Il en contient beaucoup, même en petite quantité.'], ['🔥', 'Il réchauffe', 'Il donne une sensation de chaleur dans tout le corps.'], ['🧂', 'Moins de sel', 'Il donne tellement de goût qu’on peut saler moins.']],
      ['Chips au piment d’Espelette', ['Demande à un adulte de couper une pomme de terre en tranches très fines.', 'Mélange-les avec un filet d’huile et une pincée de piment d’Espelette.', 'Étale-les sur une plaque de four.', 'Un adulte les fait cuire 20 minutes à 200 °C.']]),
    brocoli: K('Le brocoli', 'Le brocoli ressemble à un petit arbre ! Ce légume d’automne est un vrai trésor de vitamines.',
      ['Quelle partie du brocoli mange-t-on ?', ['Ses racines', 'Ses fleurs pas encore ouvertes', 'Ses feuilles'], 1, 'Les petites boules vertes du brocoli sont des boutons de fleurs. Si on attend, elles s’ouvrent en fleurs jaunes !'],
      'Le brocoli vient d’Italie : son nom veut dire « petite pousse » en italien. Catherine de Médicis l’aurait fait connaître en France.',
      'En France, il pousse surtout en Bretagne, où le climat doux lui convient bien.',
      'Le brocoli est un cousin du chou-fleur, du chou de Bruxelles et du chou vert : ils sont tous de la famille des choux !',
      [['🛡️', 'Plein de vitamine C', 'Plus que l’orange, à poids égal !'], ['🦴', 'Des os solides', 'Il contient du calcium et de la vitamine K.'], ['🌾', 'Des fibres', 'Pour un ventre en pleine forme.']],
      ['Brocoli gratiné', ['Un adulte fait cuire des bouquets de brocoli 5 minutes à la vapeur.', 'Mets-les dans un plat.', 'Parsème de fromage râpé.', 'Un adulte passe le plat 5 minutes sous le grill du four.']]),
    chou: K('Le chou vert', 'Le chou vert est le roi de l’hiver : il résiste au froid et même au gel dans les champs !',
      ['Quel légume est de la même famille que le chou ?', ['La carotte', 'Le radis', 'La tomate'], 1, 'Le radis, le navet, le brocoli et la moutarde sont tous des cousins du chou : la famille des Brassicacées.'],
      'Le chou est l’un des plus vieux légumes d’Europe. Les Grecs et les Romains le cultivaient déjà il y a plus de 2 000 ans.',
      'En France, on le cultive dans beaucoup de régions, surtout en Bretagne, dans le Nord et en Alsace.',
      'Le gel ne fait pas peur au chou : il le rend même plus sucré ! C’est pour ça qu’il est meilleur en hiver.',
      [['🛡️', 'Vitamine C', 'Pour passer l’hiver sans attraper froid.'], ['🌾', 'Des fibres', 'Pour aider ton ventre à bien digérer.'], ['🦴', 'Vitamine K', 'Pour des os solides.']],
      ['Chips de chou', ['Lave quelques feuilles de chou et sèche-les bien.', 'Déchire-les en morceaux, sans les grosses tiges.', 'Mélange avec un peu d’huile et une pincée de sel.', 'Un adulte les fait cuire 10 minutes au four à 180 °C.']]),
    laitue: K('La laitue', 'Tendre et croquante, la laitue est la salade qu’on voit le plus souvent. Elle est à son meilleur au printemps.',
      ['D’où vient le mot « laitue » ?', ['Du lait', 'D’une ville italienne', 'Du mot « lettre »'], 0, 'Quand on coupe sa tige, il en sort un jus blanc comme du lait. Son nom vient du latin « lac », qui veut dire lait.'],
      'La laitue était déjà cultivée par les Égyptiens il y a plus de 4 000 ans. On la retrouve même dessinée dans leurs tombeaux !',
      'Elle pousse partout en France, surtout dans le Sud-Est, en Bretagne et en Île-de-France.',
      'Il existe beaucoup de sortes de laitues : la batavia, la feuille de chêne, la romaine… Chacune a sa forme et son goût.',
      [['💧', 'Pleine d’eau', 'Elle est faite à 95 % d’eau.'], ['🦴', 'Vitamine K', 'Elle aide tes os à rester solides.'], ['🪶', 'Toute légère', 'Tu peux en manger beaucoup !']],
      ['Wraps de salade', ['Lave et sèche quelques grandes feuilles de laitue.', 'Pose sur chacune un peu de poulet ou de thon, et des dés de tomate.', 'Ajoute une cuillère de fromage blanc.', 'Roule la feuille comme un wrap et croque !']]),
    epinard: K('L’épinard', 'Les épinards sont des feuilles vert foncé qu’on mange au printemps et en automne, crues ou cuites.',
      ['Quel héros de dessin animé devient super fort en mangeant des épinards ?', ['Tintin', 'Popeye', 'Astérix'], 1, 'Popeye le marin avale une boîte d’épinards pour gagner des super muscles !'],
      'Les épinards viennent de Perse, l’Iran d’aujourd’hui. Ils sont arrivés en Europe au Moyen Âge.',
      'En France, ils poussent surtout dans le Nord, en Bretagne et dans la région d’Avignon.',
      'Les épinards rétrécissent énormément en cuisant : un gros saladier d’épinards crus donne à peine un bol une fois cuits !',
      [['💪', 'Du fer', 'Il aide ton sang à transporter l’oxygène dans ton corps.'], ['👀', 'Bons pour les yeux', 'Ils contiennent des antioxydants qui protègent ta vue.'], ['🦴', 'Vitamine K', 'Pour des os solides.']],
      ['Pancakes verts', ['Mixe une poignée d’épinards crus avec un œuf et un verre de lait.', 'Ajoute 4 cuillères de farine et mélange.', 'Un adulte fait cuire de petites crêpes dans une poêle.', 'Garnis-les de fromage frais !']]),
    'pomme-de-terre': K('La pomme de terre', 'Frites, purée, gratin… La pomme de terre se cuisine de mille façons. Les nouvelles récoltes arrivent à la fin de l’été.',
      ['Quelle partie de la plante est la pomme de terre ?', ['Une racine', 'Un tubercule', 'Un fruit'], 1, 'La pomme de terre est un tubercule : une réserve de nourriture que la plante fabrique sous terre, au bout de ses tiges.'],
      'La pomme de terre vient des Andes, en Amérique du Sud. En France, les gens s’en méfiaient, jusqu’à ce que Parmentier la fasse aimer au XVIIIᵉ siècle.',
      'Elle pousse dans toute la France, surtout dans les Hauts-de-France, la première région productrice du pays.',
      'Selon la légende, Parmentier faisait garder son champ de pommes de terre par des soldats le jour… mais pas la nuit. Les curieux venaient alors en voler !',
      [['⚡', 'De l’énergie', 'Pour jouer et faire du sport.'], ['💪', 'Du potassium', 'Pour des muscles qui fonctionnent bien.'], ['🛡️', 'Vitamine C', 'Surtout quand on la cuit avec sa peau.']],
      ['Pommes de terre en robe des champs', ['Lave bien des pommes de terre, sans les éplucher.', 'Un adulte les fait cuire 25 minutes dans l’eau bouillante.', 'Coupe-les en deux.', 'Garnis de fromage blanc à la ciboulette !']]),
    mais: K('Le maïs doux', 'Le maïs doux est plein de petits grains jaunes et sucrés. On le mange grillé ou en salade à la fin de l’été.',
      ['Que se passe-t-il quand on chauffe certains grains de maïs ?', ['Ils fondent', 'Ils éclatent en pop-corn', 'Ils deviennent bleus'], 1, 'Le pop-corn vient d’une variété spéciale de maïs : avec la chaleur, l’eau du grain se transforme en vapeur et le fait éclater !'],
      'Le maïs vient du Mexique, où il est cultivé depuis plus de 7 000 ans. C’était l’aliment le plus important des Mayas et des Aztèques.',
      'En France, le maïs doux pousse surtout dans le Sud-Ouest, dans les Landes et en Aquitaine.',
      'Un épi de maïs a presque toujours un nombre pair de rangées de grains !',
      [['⚡', 'De l’énergie', 'Parfait pour les journées bien remplies.'], ['🌾', 'Des fibres', 'Pour un ventre en forme.'], ['👀', 'Bon pour les yeux', 'Sa couleur jaune vient d’antioxydants.']],
      ['Épis grillés au beurre', ['Un adulte fait cuire les épis 10 minutes dans l’eau bouillante.', 'Laisse-les tiédir un peu.', 'Étale un peu de beurre avec un pinceau.', 'Ajoute une pincée de sel et croque !']]),
    'petit-pois': K('Le petit pois', 'Les petits pois sont cachés dans une cosse, comme un trésor. On les écosse au début de l’été.',
      ['Que veut dire « écosser » ?', ['Ouvrir la cosse pour sortir les pois', 'Faire cuire les pois', 'Planter les pois'], 0, 'Écosser, c’est ouvrir la gousse avec les doigts pour récupérer les petits pois. Une activité parfaite à faire en famille !'],
      'Le petit pois est cultivé depuis la Préhistoire. Mais c’est le roi Louis XIV qui l’a mis à la mode : à Versailles, tout le monde en raffolait !',
      'En France, il pousse surtout dans le Nord, en Picardie et dans le Centre.',
      'Le petit pois est une graine ! Il fait partie de la même famille que les haricots et les lentilles.',
      [['💪', 'Des protéines', 'Pour construire tes muscles.'], ['🌾', 'Des fibres', 'Pour un ventre en forme.'], ['⚡', 'De l’énergie', 'Pour tenir toute la journée.']],
      ['L’atelier écossage', ['Mets une montagne de cosses sur la table.', 'Ouvre chaque cosse avec le pouce.', 'Fais tomber les petits pois dans un saladier… et compte-les !', 'Un adulte les fait cuire 10 minutes avec un peu de beurre.']]),
    'haricot-vert': K('Le haricot vert', 'Longs, fins et croquants, les haricots verts sont les stars du potager en plein été.',
      ['Le haricot vert, c’est…', ['La tige de la plante', 'Une gousse avec des graines dedans', 'Une racine'], 1, 'On mange la gousse entière, avec les petites graines à l’intérieur. Si on la laisse grandir, les graines deviennent des haricots secs !'],
      'Le haricot vient d’Amérique centrale et du Sud. Il est arrivé en France au XVIᵉ siècle.',
      'En France, il pousse surtout en Bretagne, dans les Hauts-de-France et le Val de Loire.',
      'Avant de les cuire, il faut les « équeuter » : enlever les deux petites pointes au bout. Une tâche parfaite pour aider en cuisine !',
      [['🌾', 'Des fibres', 'Pour aider ton ventre.'], ['🦴', 'Vitamine K', 'Pour des os solides.'], ['🪶', 'Léger', 'Beaucoup de goût pour peu de calories.']],
      ['Salade de haricots verts', ['Équeute les haricots verts.', 'Un adulte les fait cuire 8 minutes dans l’eau bouillante salée.', 'Plonge-les dans l’eau froide pour qu’ils restent bien verts.', 'Ajoute des tomates cerises et un filet de vinaigrette.']]),
    potiron: K('Le potiron', 'Gros, rond et orange, le potiron est la star de l’automne. On en fait des soupes toutes douces.',
      ['Combien peut peser le plus gros potiron du monde ?', ['10 kilos', '100 kilos', 'Plus de 1 000 kilos'], 2, 'Les champions des concours dépassent 1 000 kilos : autant qu’une petite voiture !'],
      'Le potiron vient d’Amérique. Il est arrivé en Europe au XVIᵉ siècle. Pendant longtemps, on le donnait surtout aux animaux !',
      'En France, on le cultive surtout dans l’Ouest, en Pays de la Loire et en Nouvelle-Aquitaine.',
      'Potiron et citrouille, ce n’est pas pareil ! Le potiron a une tige ronde et tendre, la citrouille une tige dure et carrée.',
      [['👀', 'Bon pour les yeux', 'Sa couleur orange vient du bêta-carotène.'], ['🛡️', 'Des vitamines', 'Pour rester en forme en automne.'], ['🪶', 'Tout doux', 'Il est léger et facile à digérer.']],
      ['Velouté de potiron', ['Un adulte enlève la peau du potiron et le coupe en cubes.', 'Mets les cubes dans une casserole et couvre d’eau.', 'Fais cuire 20 minutes avec un adulte.', 'Mixe avec un peu de crème : c’est prêt !']]),
    ail: K('L’ail', 'Petit mais puissant, l’ail donne beaucoup de goût. Il est récolté en été, puis séché pour se garder toute l’année.',
      ['Comment s’appellent les morceaux d’une tête d’ail ?', ['Des gousses', 'Des caïeux', 'Les deux !'], 2, 'On dit une gousse d’ail, mais les jardiniers disent aussi un « caïeu ». Une tête en contient une dizaine.'],
      'L’ail vient d’Asie centrale. Les ouvriers qui ont construit les pyramides d’Égypte en mangeaient pour avoir de la force !',
      'En France, il pousse surtout dans le Sud-Ouest. L’ail rose de Lautrec et l’ail violet de Cadours sont très célèbres.',
      'Dans les légendes, l’ail sert à faire fuir les vampires !',
      [['🛡️', 'Il protège', 'Il aide ton corps à se défendre contre les microbes.'], ['❤️', 'Bon pour le cœur', 'Il aide le sang à bien circuler.'], ['🧂', 'Plein de goût', 'Avec lui, pas besoin de beaucoup de sel.']],
      ['Pain à l’ail', ['Un adulte fait griller des tranches de pain.', 'Coupe une gousse d’ail en deux.', 'Frotte l’ail sur le pain chaud.', 'Ajoute un filet d’huile d’olive et des morceaux de tomate !']]),
    oignon: K('L’oignon', 'L’oignon est dans presque toutes les recettes salées. On le récolte à la fin de l’été et il se garde des mois.',
      ['Pourquoi pleure-t-on en coupant un oignon ?', ['Parce qu’on est triste', 'Il libère un gaz qui pique les yeux', 'À cause de sa couleur'], 1, 'Quand on le coupe, l’oignon libère un gaz qui irrite les yeux. Astuce : mets-le au frigo avant de le couper !'],
      'L’oignon est cultivé depuis plus de 5 000 ans. Les Égyptiens le trouvaient si précieux qu’ils en mettaient dans les tombeaux des pharaons.',
      'En France, il pousse surtout dans le Nord, en Picardie et en Champagne. L’oignon doux des Cévennes a une AOP.',
      'L’oignon est un bulbe : une réserve de nourriture en couches. Coupe-le en deux pour voir tous ses anneaux !',
      [['🛡️', 'Il protège', 'Il contient des antioxydants.'], ['❤️', 'Bon pour le cœur', 'Il aide le sang à bien circuler.'], ['🌾', 'Des fibres', 'Pour un ventre en forme.']],
      ['Oignons caramélisés', ['Un adulte coupe deux oignons en fines lamelles.', 'Fais-les cuire doucement à la poêle avec un peu de beurre, avec un adulte.', 'Remue souvent pendant 20 minutes.', 'Ils deviennent tout dorés et sucrés : mets-les dans un burger !']]),
    champignon: K('Le champignon de Paris', 'Le champignon de Paris est tout blanc et tout doux. Il pousse toute l’année, mais on le mange surtout en automne.',
      ['Le champignon, c’est un légume ?', ['Oui, un légume', 'Non, ce n’est même pas une plante', 'C’est un fruit'], 1, 'Les champignons ne sont ni des plantes ni des animaux : ils forment un groupe à part, le règne des champignons !'],
      'Au XVIIᵉ siècle, les jardiniers de Louis XIV ont appris à le cultiver. Plus tard, on l’a fait pousser dans les anciennes carrières sous Paris : d’où son nom !',
      'Aujourd’hui, il pousse surtout dans les caves et les carrières de la vallée de la Loire, autour de Saumur.',
      'Les champignons n’ont pas besoin de lumière pour pousser : ils aiment le noir et l’humidité.',
      [['🪶', 'Très léger', 'Il contient beaucoup d’eau et très peu de calories.'], ['⚡', 'Vitamines B', 'Elles t’aident à avoir de l’énergie.'], ['🦴', 'Vitamine D', 'Une vitamine rare, bonne pour les os.']],
      ['Champignons farcis', ['Enlève le pied des champignons.', 'Remplis chaque chapeau de fromage frais aux herbes.', 'Pose-les sur une plaque de four.', 'Un adulte les fait cuire 15 minutes à 180 °C.']]),
    'patate-douce': K('La patate douce', 'Orange à l’intérieur et naturellement sucrée, la patate douce est parfaite en purée ou en frites en hiver.',
      ['La patate douce est-elle de la même famille que la pomme de terre ?', ['Oui, ce sont des sœurs', 'Non, pas du tout', 'C’est une pomme de terre peinte'], 1, 'Malgré son nom, elle n’est pas de la même famille que la pomme de terre. Elle est plutôt cousine du liseron, une fleur des jardins !'],
      'La patate douce vient d’Amérique centrale. Christophe Colomb l’a rapportée en Europe avant même la pomme de terre !',
      'Celle qu’on mange en France vient souvent d’Espagne ou d’Amérique, mais on commence à en cultiver dans le Sud-Ouest.',
      'Ses feuilles se mangent aussi ! Dans certains pays d’Afrique et d’Asie, on les cuisine comme des épinards.',
      [['👀', 'Bonne pour les yeux', 'Sa chair orange est pleine de bêta-carotène.'], ['⚡', 'De l’énergie', 'Une énergie qui dure longtemps.'], ['🌾', 'Des fibres', 'Pour un ventre en forme.']],
      ['Frites de patate douce', ['Un adulte épluche la patate douce et la coupe en frites.', 'Mélange-les avec un filet d’huile et une pincée de sel.', 'Étale-les sur une plaque de four.', 'Un adulte les fait cuire 25 minutes à 200 °C.']]),
    fraise: K('La fraise', 'Rouge, parfumée et sucrée, la fraise annonce le printemps. Elle est à son meilleur en mai et en juin.',
      ['Où sont les vrais fruits de la fraise ?', ['Au centre', 'Ce sont les petits points sur sa peau', 'Elle n’en a pas'], 1, 'Les petits points sur la fraise sont ses vrais fruits : des akènes, qui contiennent chacun une graine. Il y en a environ 200 par fraise !'],
      'Les fraises des bois existent depuis toujours. La grosse fraise d’aujourd’hui est née il y a 300 ans, en mélangeant une fraise d’Amérique du Nord et une fraise du Chili.',
      'En France, elle pousse surtout dans le Sud-Ouest, en Lot-et-Garonne et en Dordogne, et aussi à Plougastel, en Bretagne.',
      'Pour les botanistes, la partie rouge de la fraise n’est pas le fruit : c’est le cœur de la fleur, qui a gonflé !',
      [['🛡️', 'Vitamine C', 'Une poignée de fraises en contient autant qu’une orange !'], ['🪶', 'Légère', 'Elle est peu sucrée pour un fruit.'], ['❤️', 'Antioxydants', 'Sa couleur rouge protège tes cellules.']],
      ['Fraises au chocolat', ['Lave les fraises et enlève les queues.', 'Pique-les sur des bâtonnets.', 'Un adulte fait fondre un peu de chocolat.', 'Trempe le bout des fraises dedans et mets au frais 10 minutes.']]),
    cerise: K('La cerise', 'Petite, rouge et brillante, la cerise ne reste que quelques semaines, au début de l’été. Il faut en profiter !',
      ['Qu’y a-t-il au milieu d’une cerise ?', ['Des pépins', 'Un noyau', 'Rien'], 1, 'La cerise a un noyau dur au centre : c’est une drupe, comme la pêche et l’abricot.'],
      'Les cerisiers sauvages poussaient déjà en Europe à la Préhistoire. Il y a 2 000 ans, le général romain Lucullus a rapporté de Turquie une variété plus sucrée.',
      'En France, elles poussent surtout dans le Sud-Est, en Provence et dans la vallée du Rhône. Céret, dans les Pyrénées-Orientales, donne les premières de l’année.',
      'Au Japon, la floraison des cerisiers est une grande fête : chaque printemps, les familles pique-niquent sous les arbres en fleurs.',
      [['😴', 'Aide à dormir', 'Elle contient un peu de mélatonine, l’hormone du sommeil.'], ['❤️', 'Antioxydants', 'Sa couleur rouge foncé protège tes cellules.'], ['💪', 'Du potassium', 'Pour des muscles en forme.']],
      ['Clafoutis aux cerises', ['Lave les cerises et mets-les dans un plat beurré.', 'Mélange 3 œufs, 60 g de sucre, 60 g de farine et 25 cl de lait.', 'Verse la pâte sur les cerises.', 'Un adulte le fait cuire 35 minutes à 180 °C.']]),
    peche: K('La pêche', 'Juteuse et parfumée, la pêche a une peau toute douce, comme du velours. C’est un fruit du plein été.',
      ['Comment s’appelle une pêche à la peau lisse ?', ['Une nectarine ou un brugnon', 'Un abricot', 'Une prune'], 0, 'La nectarine et le brugnon sont des pêches à la peau lisse, sans duvet.'],
      'La pêche vient de Chine, où elle est cultivée depuis plus de 4 000 ans. Là-bas, elle est le symbole d’une longue vie.',
      'En France, elle pousse surtout dans la vallée du Rhône, dans le Roussillon et en Provence.',
      'Les Romains l’appelaient « pomme de Perse », car ils croyaient qu’elle venait d’Iran. C’est de là que vient son nom !',
      [['💧', 'Pleine d’eau', 'Elle hydrate pendant les chaudes journées.'], ['👀', 'Bonne pour les yeux', 'Elle contient du bêta-carotène.'], ['🛡️', 'Vitamine C', 'Pour aider ton corps à se défendre.']],
      ['Pêches rôties au miel', ['Un adulte coupe les pêches en deux et enlève le noyau.', 'Pose-les dans un plat, la face coupée vers le haut.', 'Ajoute une cuillère de miel sur chacune.', 'Un adulte les fait cuire 20 minutes à 180 °C.']]),
    melon: K('Le melon', 'Sucré, juteux et plein d’eau : le melon est le fruit parfait quand il fait chaud. On le mange surtout en juillet et en août.',
      ['Le melon, c’est un fruit ou un légume ?', ['Un fruit', 'Un légume', 'Les deux !'], 2, 'Pour les botanistes, c’est un légume : il est de la même famille que la courgette et le concombre. Mais comme il est sucré, on le mange comme un fruit, au dessert !'],
      'Le melon vient d’Afrique ou d’Asie. Les Égyptiens le cultivaient déjà il y a presque 5 000 ans ! Il est arrivé en France il y a environ 500 ans, et les rois en raffolaient.',
      'Il aime le soleil ! En France, il pousse surtout dans le Sud, près de Cavaillon, et dans l’Ouest, dans le Poitou.',
      'L’écrivain Alexandre Dumas, l’auteur des Trois Mousquetaires, aimait tellement le melon qu’il a donné tous ses livres à la ville de Cavaillon… en échange de 12 melons par an !',
      [['💧', 'Il hydrate', 'Presque tout le melon est de l’eau. Parfait après le sport !'], ['👀', 'Bon pour les yeux', 'Sa couleur orange vient du bêta-carotène, comme la carotte.'], ['🛡️', 'Il protège', 'Sa vitamine C aide ton corps à se défendre contre les microbes.']],
      ['Brochettes melon-fraise', ['Demande à un adulte de couper le melon en cubes.', 'Lave les fraises et enlève les queues.', 'Pique les morceaux sur des bâtonnets, en alternant les couleurs.', 'Mets au frais 15 minutes… et régale-toi !']]),
    pasteque: K('La pastèque', 'Énorme, rouge et pleine d’eau, la pastèque est le fruit le plus rafraîchissant de l’été.',
      ['Combien d’eau contient une pastèque ?', ['Environ 50 %', 'Environ 75 %', 'Plus de 90 %'], 2, 'La pastèque contient environ 92 % d’eau : c’est presque un verre d’eau à croquer !'],
      'La pastèque vient d’Afrique. Les Égyptiens la cultivaient déjà il y a 4 000 ans et en mettaient dans les tombeaux des pharaons.',
      'Celle qu’on mange en France vient souvent d’Espagne, mais on en cultive aussi dans le Sud, en Provence et dans le Roussillon.',
      'Au Japon, certains agriculteurs font pousser des pastèques carrées, en les plaçant dans des boîtes !',
      [['💧', 'Super hydratante', 'Idéale quand il fait très chaud.'], ['❤️', 'Du lycopène', 'Le même pigment rouge que la tomate, qui protège ton corps.'], ['🪶', 'Légère', 'Peu de calories pour beaucoup de plaisir.']],
      ['Sucettes de pastèque', ['Un adulte coupe la pastèque en triangles épais.', 'Fais une petite fente dans la peau de chaque triangle.', 'Plante un bâtonnet de glace dedans.', 'Mets-les 1 heure au congélateur : c’est une glace naturelle !']]),
    myrtille: K('La myrtille', 'Petite baie bleue qui tache les doigts, la myrtille se cueille en montagne à la fin de l’été.',
      ['Que se passe-t-il quand on mange beaucoup de myrtilles sauvages ?', ['La langue devient bleue', 'On grandit plus vite', 'Les cheveux poussent'], 0, 'La myrtille sauvage est bleue jusqu’au cœur : elle colore la langue, les dents et les doigts !'],
      'Les myrtilles poussent à l’état sauvage dans les forêts d’Europe depuis toujours. Pendant très longtemps, on allait seulement les cueillir dans la nature.',
      'En France, les myrtilles sauvages poussent en montagne : dans les Vosges, le Massif central, les Alpes et les Pyrénées.',
      'On raconte que des pilotes de la Seconde Guerre mondiale mangeaient des myrtilles pour mieux voir la nuit. C’est une légende… mais elles sont vraiment bonnes pour les yeux !',
      [['👀', 'Bonne pour les yeux', 'Ses pigments bleus protègent ta vue.'], ['🧠', 'Pour le cerveau', 'Ses antioxydants protègent tes cellules.'], ['🛡️', 'Vitamine C', 'Pour aider ton corps à se défendre.']],
      ['Yaourt glacé aux myrtilles', ['Mélange un yaourt nature avec une poignée de myrtilles.', 'Ajoute une cuillère de miel.', 'Étale le mélange sur une plaque recouverte de papier cuisson.', 'Mets 2 heures au congélateur, puis casse en morceaux !']]),
    raisin: K('Le raisin', 'En grappes vertes ou violettes, le raisin arrive en septembre, au moment des vendanges.',
      ['Comment appelle-t-on la récolte du raisin ?', ['La moisson', 'Les vendanges', 'La cueillette d’or'], 1, 'Les vendanges ont lieu en septembre et en octobre. Le raisin sert à faire du jus… et du vin pour les adultes.'],
      'La vigne est cultivée depuis plus de 7 000 ans. Ce sont les Grecs puis les Romains qui l’ont plantée en France.',
      'En France, le raisin de table pousse surtout dans le Sud : le chasselas de Moissac et le muscat du Ventoux ont une AOP.',
      'Les raisins secs sont simplement des raisins séchés au soleil. Il faut environ 4 kilos de raisin frais pour faire 1 kilo de raisins secs !',
      [['⚡', 'De l’énergie', 'Son sucre naturel donne un coup de boost.'], ['❤️', 'Antioxydants', 'Surtout dans les raisins noirs, pour protéger ton cœur.'], ['💧', 'Plein d’eau', 'Il désaltère.']],
      ['Raisins glacés', ['Lave et détache les grains de raisin.', 'Sèche-les bien.', 'Mets-les 2 heures dans une boîte au congélateur.', 'Croque-les comme des bonbons glacés !']]),
    pomme: K('La pomme', 'Croquante, juteuse, sucrée ou acidulée : la pomme est le fruit préféré des Français. Sa saison commence en septembre.',
      ['Combien de variétés de pommes existe-t-il dans le monde ?', ['Une dizaine', 'Une centaine', 'Plusieurs milliers'], 2, 'Il existe des milliers de variétés de pommes : Gala, Golden, Reinette, Pink Lady… Chacune a son goût !'],
      'La pomme vient du Kazakhstan, en Asie centrale, où poussent encore des forêts de pommiers sauvages. Elle a voyagé jusqu’en Europe par la route de la soie.',
      'En France, elle pousse surtout dans le Val de Loire, le Sud-Est, le Limousin et la Normandie. La pomme du Limousin a une AOP.',
      'Une pomme flotte dans l’eau, car elle contient environ 25 % d’air ! C’est pour ça qu’on peut jouer à les attraper avec la bouche dans une bassine.',
      [['🌾', 'Des fibres', 'Surtout dans la peau : croque-la avec !'], ['🦷', 'Croquante', 'Elle fait travailler tes dents.'], ['⚡', 'De l’énergie', 'Parfaite pour le goûter.']],
      ['Pommes au four', ['Un adulte enlève le cœur des pommes avec un vide-pomme.', 'Mets-les dans un plat.', 'Remplis le trou avec un peu de beurre, de sucre et de cannelle.', 'Un adulte les fait cuire 30 minutes à 180 °C.']]),
    poire: K('La poire', 'Fondante et juteuse, la poire arrive au début de l’automne. On l’aime bien mûre, quand elle est toute douce.',
      ['Comment savoir si une poire est mûre ?', ['Elle devient bleue', 'Elle est un peu molle près de la queue', 'Elle fait du bruit'], 1, 'Appuie doucement près de la queue : si c’est un peu mou, la poire est prête à croquer !'],
      'La poire est cultivée depuis l’Antiquité. Louis XIV l’adorait : dans son potager de Versailles, on en cultivait des centaines de variétés.',
      'En France, elle pousse surtout dans le Sud-Est, la vallée du Rhône et le Val de Loire.',
      'La poire mûrit mieux après avoir été cueillie ! On la ramasse encore dure et elle devient fondante en quelques jours.',
      [['🌾', 'Des fibres', 'Pour un ventre en forme.'], ['💧', 'Pleine d’eau', 'Elle hydrate et elle est douce pour le ventre.'], ['💪', 'Du potassium', 'Pour des muscles en forme.']],
      ['Poires au chocolat', ['Un adulte épluche les poires et les coupe en quartiers.', 'Mets-les dans des coupelles.', 'Un adulte fait fondre un peu de chocolat.', 'Verse le chocolat dessus : c’est une poire Belle-Hélène facile !']]),
    chataigne: K('La châtaigne', 'Brillante et marron, la châtaigne tombe des arbres en automne, cachée dans une bogue pleine de piquants.',
      ['Le marron d’Inde qu’on ramasse dans les parcs, ça se mange ?', ['Oui, c’est pareil qu’une châtaigne', 'Non, il est toxique', 'Seulement cuit'], 1, 'Le marron d’Inde est toxique : il ne faut jamais le manger ! Les « marrons » qu’on mange à Noël sont en fait de grosses châtaignes.'],
      'La châtaigne a nourri des villages entiers pendant des siècles, dans les montagnes. On appelait le châtaignier « l’arbre à pain ».',
      'En France, elle pousse surtout en Ardèche, dans les Cévennes, en Corse et dans le Limousin. La châtaigne d’Ardèche a une AOP.',
      'Avant de faire griller une châtaigne, il faut l’entailler, sinon elle explose avec la chaleur !',
      [['⚡', 'De l’énergie', 'Elle est riche en amidon, comme les céréales.'], ['🌾', 'Des fibres', 'Pour un ventre en forme.'], ['💪', 'Des minéraux', 'Du potassium et du magnésium pour tes muscles.']],
      ['Châtaignes grillées', ['Un adulte fait une entaille en croix sur chaque châtaigne.', 'Mets-les sur une plaque de four.', 'Un adulte les fait cuire 25 minutes à 200 °C.', 'Épluche-les encore tièdes et régale-toi !']]),
    kiwi: K('Le kiwi', 'Poilu à l’extérieur, vert et acidulé à l’intérieur, le kiwi est un fruit d’hiver plein de vitamines.',
      ['D’où vient le nom « kiwi » ?', ['D’un oiseau de Nouvelle-Zélande', 'D’une ville chinoise', 'Du bruit qu’il fait'], 0, 'Les Néo-Zélandais lui ont donné le nom de leur oiseau national, le kiwi : petit, marron et poilu… comme le fruit !'],
      'Le kiwi vient de Chine, où on l’appelait « groseille de Chine ». Il a été cultivé en Nouvelle-Zélande il y a environ 100 ans, puis il est arrivé en France.',
      'En France, il pousse surtout dans le Sud-Ouest, dans les Landes et au Pays basque. Le kiwi de l’Adour a une IGP.',
      'Un seul kiwi contient presque toute la vitamine C dont tu as besoin dans la journée !',
      [['🛡️', 'Champion de la vitamine C', 'Pour passer l’hiver en pleine forme.'], ['🌾', 'Des fibres', 'Pour un ventre en forme.'], ['🦴', 'Vitamine K', 'Pour des os solides.']],
      ['Kiwi à la coque', ['Coupe le haut du kiwi, comme un œuf à la coque.', 'Pose-le dans un coquetier.', 'Mange-le à la petite cuillère.', 'Essaie aussi avec une pincée de sucre !']]),
    clementine: K('La clémentine', 'Petite, sucrée et facile à éplucher, la clémentine est le fruit star de Noël.',
      ['Qui a découvert la clémentine ?', ['Un roi', 'Un moine', 'Un pirate'], 1, 'Vers 1900, en Algérie, le frère Clément a trouvé ce nouveau fruit dans le jardin de son orphelinat. On lui a donné son nom !'],
      'La clémentine est un fruit tout récent : elle est née il y a un peu plus de 100 ans. Elle est vite devenue un classique des fêtes de fin d’année.',
      'En France, elle pousse en Corse. La clémentine de Corse a une IGP.',
      'La clémentine de Corse est vendue avec ses feuilles : c’est la preuve qu’elle a été cueillie il y a peu de temps !',
      [['🛡️', 'Vitamine C', 'Pour résister aux rhumes de l’hiver.'], ['⚡', 'De l’énergie', 'Parfaite pour le goûter ou la récré.'], ['🌾', 'Des fibres', 'Surtout dans les petites peaux blanches.']],
      ['Clémentines-citrouilles', ['Épluche des clémentines sans abîmer les quartiers.', 'Coupe un petit morceau de branche de céleri.', 'Plante-le au milieu, comme une tige.', 'Présente-les à table : effet garanti !']]),
    orange: K('L’orange', 'Juteuse et pleine de soleil, l’orange est le fruit de l’hiver. Les oranges sanguines, rouges à l’intérieur, arrivent en janvier.',
      ['Qu’est-ce qui a été nommé en premier : la couleur ou le fruit ?', ['La couleur', 'Le fruit', 'Les deux en même temps'], 1, 'C’est le fruit qui a donné son nom à la couleur orange !'],
      'L’orange douce vient de Chine. Elle est arrivée en Europe au XVᵉ siècle avec les navigateurs portugais. À Noël, c’était autrefois un cadeau très précieux !',
      'Les oranges qu’on mange en France viennent surtout d’Espagne, d’Italie et du Maroc, où il fait chaud en hiver.',
      'Dans les pays très chauds, les oranges restent parfois vertes, même mûres ! C’est la fraîcheur des nuits qui les rend orange.',
      [['🛡️', 'Vitamine C', 'Pour aider ton corps à se défendre en hiver.'], ['💧', 'Pleine de jus', 'Elle hydrate.'], ['🌾', 'Des fibres', 'Mange-la entière plutôt qu’en jus !']],
      ['Jus d’orange maison', ['Un adulte coupe les oranges en deux.', 'Presse-les avec un presse-agrumes.', 'Filtre le jus si tu n’aimes pas la pulpe.', 'Bois-le tout de suite !']]),
    citron: K('Le citron', 'Jaune et très acide, le citron réveille toutes les recettes. Il est à son meilleur en hiver.',
      ['Pourquoi met-on du citron sur une pomme coupée ?', ['Pour la rendre sucrée', 'Pour qu’elle ne noircisse pas', 'Pour qu’elle grossisse'], 1, 'L’acidité du citron empêche la pomme, l’avocat ou la banane de devenir marron au contact de l’air.'],
      'Le citron vient d’Asie. Autrefois, les marins en emportaient sur les bateaux pour ne pas tomber malades pendant les longs voyages.',
      'Ceux qu’on mange en France viennent surtout d’Espagne, mais il existe un citron français célèbre : le citron de Menton, sur la Côte d’Azur.',
      'Avec un citron, deux pièces de métal différentes et des fils, on peut fabriquer une petite pile électrique !',
      [['🛡️', 'Vitamine C', 'Elle aide ton corps à se défendre contre les microbes.'], ['🧂', 'Plein de goût', 'Quelques gouttes suffisent pour relever un plat.'], ['💧', 'Dans l’eau', 'Un peu de citron dans l’eau donne envie de boire !']],
      ['Citronnade maison', ['Presse 2 citrons.', 'Verse le jus dans une carafe avec 1 litre d’eau.', 'Ajoute 3 cuillères de miel ou de sucre et mélange.', 'Mets au frais avec quelques feuilles de menthe.']]),
    avocat: K('L’avocat', 'Vert, crémeux et tout doux, l’avocat se mange salé. Il est à son meilleur en hiver et au printemps.',
      ['L’avocat, c’est un fruit ou un légume ?', ['Un fruit', 'Un légume', 'Une noix'], 0, 'L’avocat est un fruit : il pousse sur un arbre et contient un gros noyau. Mais on le mange comme un légume !'],
      'L’avocat vient du Mexique, où les Aztèques le cultivaient déjà. Son nom vient de leur langue : « ahuacatl ».',
      'Ceux qu’on mange en France viennent surtout d’Espagne, du Pérou ou du Mexique.',
      'Un avocat ne mûrit pas sur l’arbre : il faut le cueillir pour qu’il devienne tout doux !',
      [['❤️', 'De bonnes graisses', 'Elles sont bonnes pour ton cœur et ton cerveau.'], ['💪', 'Du potassium', 'Encore plus que la banane !'], ['🌾', 'Des fibres', 'Pour un ventre en forme.']],
      ['Guacamole facile', ['Un adulte coupe l’avocat en deux et enlève le noyau.', 'Récupère la chair avec une cuillère.', 'Écrase-la à la fourchette avec du jus de citron et une pincée de sel.', 'Trempe des bâtonnets de légumes dedans !']]),
    banane: K('La banane', 'Pratique et toute douce, la banane se mange toute l’année. Elle voyage depuis les Antilles jusqu’à nous.',
      ['La banane pousse…', ['Sur un arbre', 'Sur une plante géante sans bois', 'Sous la terre'], 1, 'Le bananier n’est pas un arbre : c’est une plante géante, sans bois, qui peut mesurer jusqu’à 8 mètres !'],
      'La banane vient d’Asie du Sud-Est. Elle a voyagé jusqu’en Afrique, puis jusqu’aux Antilles avec les navigateurs, il y a 500 ans.',
      'Les bananes françaises poussent aux Antilles, en Guadeloupe et en Martinique, où il fait chaud toute l’année.',
      'Les bananes poussent la tête en l’air ! Sur le régime, elles se tournent vers le soleil en grandissant.',
      [['⚡', 'De l’énergie', 'Les sportifs en mangent pendant les compétitions.'], ['💪', 'Du potassium', 'Pour des muscles qui fonctionnent bien.'], ['🌾', 'Douce pour le ventre', 'Elle est facile à digérer.']],
      ['Glace à la banane', ['Épluche 2 bananes bien mûres et coupe-les en rondelles.', 'Mets-les 3 heures au congélateur.', 'Un adulte les mixe jusqu’à obtenir une crème.', 'Mange tout de suite : une glace avec un seul ingrédient !']]),
    ananas: K('L’ananas', 'Avec sa couronne de feuilles, l’ananas ressemble à un roi ! Ce fruit tropical est très juteux et acidulé.',
      ['Combien de temps faut-il pour qu’un ananas pousse ?', ['1 semaine', '1 mois', 'Environ 18 mois'], 2, 'Il faut environ un an et demi pour qu’un ananas soit prêt. Et chaque plante n’en donne qu’un à la fois !'],
      'L’ananas vient d’Amérique du Sud. Christophe Colomb l’a découvert en 1493. En Europe, il était si rare qu’on en louait pour décorer les tables de fête !',
      'Celui qu’on mange en France vient souvent du Costa Rica. L’ananas Victoria, plus petit et très sucré, vient de La Réunion.',
      'On peut faire pousser un nouvel ananas en plantant sa couronne de feuilles dans la terre !',
      [['🛡️', 'Vitamine C', 'Pour aider ton corps à se défendre.'], ['🍽️', 'Aide à digérer', 'Il contient de la broméline, qui aide la digestion.'], ['💧', 'Plein de jus', 'Il hydrate.']],
      ['Brochettes tropicales', ['Un adulte épluche l’ananas et le coupe en cubes.', 'Coupe aussi une banane en rondelles.', 'Pique les morceaux sur des bâtonnets en alternant.', 'Saupoudre d’un peu de noix de coco râpée !']]),
    mangue: K('La mangue', 'Orange, juteuse et très parfumée, la mangue est un fruit des pays chauds qu’on trouve en hiver.',
      ['Dans quel pays la mangue est-elle le fruit national ?', ['L’Inde', 'La France', 'Le Canada'], 0, 'En Inde, la mangue est le fruit national. On la surnomme « la reine des fruits ».'],
      'La mangue est cultivée en Inde depuis plus de 4 000 ans. Les navigateurs portugais l’ont fait voyager en Afrique et en Amérique.',
      'Celle qu’on mange en France en hiver vient surtout du Pérou et du Brésil, mais aussi de La Réunion et des Antilles.',
      'Un manguier peut vivre plus de 300 ans et continuer à donner des fruits !',
      [['👀', 'Bonne pour les yeux', 'Sa chair orange est pleine de bêta-carotène.'], ['🛡️', 'Vitamine C', 'Pour rester en forme en hiver.'], ['🌾', 'Des fibres', 'Pour un ventre en forme.']],
      ['Lassi à la mangue', ['Un adulte épluche la mangue et coupe la chair en morceaux.', 'Mets-la dans un mixeur avec un yaourt et un peu de lait.', 'Un adulte mixe le tout.', 'Verse dans un verre : c’est une boisson d’Inde !']]),
    basilic: K('Le basilic', 'Très parfumé, le basilic est l’herbe de l’été. Il adore le soleil… et la tomate !',
      ['Que veut dire « basilic » ?', ['Royal', 'Petite feuille', 'Herbe verte'], 0, 'Son nom vient du grec « basilikon », qui veut dire « royal ». C’est l’herbe des rois !'],
      'Le basilic vient d’Inde, où il est considéré comme une plante sacrée. Il est arrivé en Europe il y a plus de 2 000 ans.',
      'En France, il pousse surtout en Provence. Tu peux aussi le faire pousser en pot, sur un rebord de fenêtre au soleil !',
      'Il ne faut pas mettre le basilic au frigo : il noircit avec le froid ! Mets-le dans un verre d’eau, comme un bouquet.',
      [['🦴', 'Vitamine K', 'Pour des os solides.'], ['🛡️', 'Antioxydants', 'Ils protègent tes cellules.'], ['🧂', 'Plein de goût', 'Pas besoin de beaucoup de sel avec lui.']],
      ['Pesto facile', ['Mets une grosse poignée de feuilles de basilic dans un mixeur.', 'Ajoute du parmesan râpé, une poignée de pignons et un filet d’huile d’olive.', 'Un adulte mixe le tout.', 'Mélange avec des pâtes chaudes !']]),
    menthe: K('La menthe', 'Fraîche comme une brise, la menthe parfume les salades, les boissons et les desserts en été.',
      ['Pourquoi la menthe donne-t-elle une sensation de froid ?', ['Elle est gelée', 'Elle trompe les capteurs de froid de la bouche', 'Elle contient de la glace'], 1, 'Le menthol de la menthe active les capteurs de froid de ta bouche : ton cerveau croit qu’il fait frais !'],
      'La menthe est connue depuis l’Antiquité. Les Grecs et les Romains en frottaient sur les tables pour accueillir leurs invités.',
      'Elle pousse partout en France, dans les jardins et près des ruisseaux. Elle aime l’humidité et un peu d’ombre.',
      'La menthe pousse si vite que les jardiniers la plantent en pot, pour qu’elle n’envahisse pas tout le potager !',
      [['🍽️', 'Aide à digérer', 'Une infusion de menthe fait du bien au ventre.'], ['😮‍💨', 'Haleine fraîche', 'Mâcher une feuille rafraîchit la bouche.'], ['💧', 'Donne envie de boire', 'Quelques feuilles dans l’eau, et c’est encore meilleur !']],
      ['Eau fraîche à la menthe', ['Lave une poignée de feuilles de menthe.', 'Froisse-les un peu entre tes mains pour libérer le parfum.', 'Mets-les dans une carafe d’eau avec des rondelles de citron.', 'Laisse 1 heure au frais et sers bien froid !']]),
    persil: K('Le persil', 'Plat ou frisé, le persil est l’herbe qu’on met partout. Il est à son meilleur au printemps.',
      ['Le persil est de la même famille que…', ['La carotte', 'La fraise', 'La tomate'], 0, 'Le persil, la carotte, le céleri et la coriandre sont tous de la famille des Apiacées. Regarde leurs feuilles : elles se ressemblent !'],
      'Le persil vient des bords de la mer Méditerranée. Les Grecs en faisaient des couronnes pour les champions de certains jeux sportifs !',
      'Il pousse dans toute la France, dans les champs et les jardins. Il est très facile à cultiver en pot.',
      'À poids égal, le persil contient plus de vitamine C que le citron !',
      [['🛡️', 'Vitamine C', 'Encore plus que le citron !'], ['🦴', 'Vitamine K', 'Pour des os solides.'], ['💪', 'Du fer', 'Pour transporter l’oxygène dans ton sang.']],
      ['Beurre persillé', ['Lave une poignée de persil et coupe-la finement avec des ciseaux.', 'Mélange-la avec du beurre mou.', 'Ajoute une pincée de sel.', 'Tartine sur du pain grillé ou sur des pommes de terre !']]),
    ciboulette: K('La ciboulette', 'Fine comme des brins d’herbe, la ciboulette a un petit goût d’oignon. Elle pousse dès le printemps.',
      ['La ciboulette est une cousine de…', ['L’oignon', 'La menthe', 'La salade'], 0, 'La ciboulette est de la même famille que l’oignon, l’ail et le poireau. C’est pour ça qu’elle a le même petit goût !'],
      'La ciboulette pousse à l’état sauvage en Europe et en Asie. Au Moyen Âge, on en plantait dans les jardins des monastères.',
      'Elle pousse partout en France. Tu peux facilement la faire pousser en pot, et elle repousse chaque année !',
      'Ses jolies fleurs violettes en forme de pompon se mangent aussi, en salade !',
      [['🦴', 'Vitamine K', 'Pour des os solides.'], ['🛡️', 'Vitamine C', 'Pour aider ton corps à se défendre.'], ['🧂', 'Plein de goût', 'Parfait pour saler moins.']],
      ['Fromage blanc à la ciboulette', ['Coupe la ciboulette en petits morceaux avec des ciseaux.', 'Mélange-la avec du fromage blanc.', 'Ajoute une pincée de sel et de poivre.', 'Trempe des radis ou des pommes de terre dedans !']]),
    thym: K('Le thym', 'Petit buisson aux feuilles minuscules, le thym parfume les plats du Sud. On le cueille au printemps.',
      ['Où pousse le thym à l’état sauvage ?', ['Dans la garrigue, au soleil', 'Au fond des forêts', 'Dans l’eau'], 0, 'Le thym adore les terres sèches et ensoleillées du Sud, comme la garrigue en Provence.'],
      'Les Égyptiens utilisaient déjà le thym il y a plus de 3 000 ans. Au Moyen Âge, on en offrait aux chevaliers pour leur donner du courage !',
      'En France, il pousse surtout en Provence, dans les collines. C’est l’une des fameuses herbes de Provence.',
      'Les abeilles adorent les fleurs du thym : elles en font un miel très parfumé !',
      [['🛡️', 'Doux pour la gorge', 'On en fait des infusions quand on a mal à la gorge.'], ['🍽️', 'Aide à digérer', 'Il rend les plats plus faciles à digérer.'], ['🧂', 'Plein de goût', 'Parfait pour saler moins.']],
      ['Tomates rôties au thym', ['Coupe des tomates en deux et pose-les dans un plat.', 'Parsème de feuilles de thym.', 'Ajoute un filet d’huile d’olive et une pincée de sel.', 'Un adulte les fait cuire 30 minutes à 180 °C.']]),
    gingembre: K('Le gingembre', 'Le gingembre est une drôle de racine toute biscornue qui pique un peu et parfume les plats et les boissons.',
      ['Quelle partie du gingembre mange-t-on ?', ['Ses fleurs', 'Son rhizome, une tige sous la terre', 'Ses graines'], 1, 'Ce qu’on appelle « racine » de gingembre est en fait un rhizome : une tige qui pousse sous la terre.'],
      'Le gingembre vient d’Asie du Sud-Est. On l’utilise en Chine et en Inde depuis plus de 3 000 ans, en cuisine et comme remède.',
      'Celui qu’on mange en France vient souvent du Pérou, de Chine ou d’Inde, là où il fait chaud et humide.',
      'Les bonshommes en pain d’épices s’appellent « gingerbread men » en anglais : des bonshommes au gingembre !',
      [['🍽️', 'Doux pour le ventre', 'Il calme le mal au cœur, par exemple en voiture.'], ['🔥', 'Il réchauffe', 'Parfait en infusion quand il fait froid.'], ['🛡️', 'Il protège', 'Il contient des antioxydants.']],
      ['Limonade au gingembre', ['Un adulte épluche et râpe un petit morceau de gingembre.', 'Mets-le dans une carafe avec le jus de 2 citrons.', 'Ajoute 1 litre d’eau et 3 cuillères de miel.', 'Mélange, filtre et mets au frais !']])
  };
  var lexique = {
    'agrume': 'Un fruit à la peau épaisse et parfumée, avec une chair en quartiers pleine de jus : orange, citron, clémentine…',
    'akene': 'Un tout petit fruit sec qui contient une seule graine. Les points sur la fraise sont des akènes !',
    'amaryllidacees': 'La famille de l’ail, de l’oignon et de la ciboulette. Ces plantes ont un goût fort… qui peut faire pleurer !',
    'apiacees': 'La famille de la carotte, du persil et du céleri. Leurs fleurs forment de petites ombrelles.',
    'baie': 'Un fruit charnu avec des pépins, mais sans noyau : raisin, myrtille, tomate… et même la banane !',
    'brassicacees': 'La famille des choux : brocoli, chou vert, radis, navet. Leurs fleurs ont 4 pétales en forme de croix.',
    'cucurbitacees': 'La famille des courges : potiron, courgette, melon, concombre, pastèque. Ces plantes rampent ou grimpent.',
    'drupe': 'Un fruit charnu avec un gros noyau dur au centre : cerise, pêche, abricot, mangue.',
    'fabacees': 'La famille des plantes à gousses : petit pois, haricot, lentille. Elles rendent la terre plus riche.',
    'legume-racine': 'Un légume dont on mange la racine, qui pousse sous la terre : carotte, radis, betterave.',
    'primeur': 'Un fruit ou un légume récolté tout au début de sa saison, encore jeune et tendre.',
    'rhizome': 'Une tige qui pousse sous la terre, comme une racine. Le gingembre est un rhizome.',
    'rosacees': 'La famille de la rose… mais aussi de la pomme, de la poire, de la fraise et de la cerise !',
    'solanacees': 'La famille de la tomate, de la pomme de terre, du poivron et de l’aubergine.',
    'tubercule': 'Une réserve de nourriture qu’une plante fabrique sous la terre. La pomme de terre en est un.',
    'bio': 'Ce logo vert veut dire que le produit a poussé sans pesticides chimiques ni engrais chimiques.',
    'aop': 'Un produit qui vient d’une région précise, fait avec le savoir-faire de là-bas. Exemple : le piment d’Espelette.',
    'igp': 'Un produit lié à une région qui lui donne sa qualité. Exemple : la clémentine de Corse.',
    'label-rouge': 'Un label qui garantit un goût et une qualité supérieurs aux produits ordinaires.',
    'hve': 'Un label pour les fermes qui protègent la nature : les insectes, l’eau et les sols.',
    'origine-france': 'Ce logo garantit que le fruit ou le légume a poussé en France.'
  };
  window.SAISON_ENFANTS = { produits: produits, lexique: lexique };
})();
